GET http://localhost:9876/send-message?chatId=-601860434&msg=@Rtm_Zz hi2

###
POST http://localhost:9876/civ6
Content-Type: application/json

{
  "Value1": "Game Name",
  "Value2": "Player Name",
  "Value3": "Turn Number",
  "unknown_prop": 123
}

###
POST http://91.196.248.242:9876/civ6
Content-Type: application/json

{
  "Value1": "Game Name",
  "Value2": "Player Name",
  "Value3": "Turn Number"
}

###
POST http://91.196.248.242:9876/civ6
Content-Type: application/json

{
  "value1": "Game Name",
  "value2": "Player Name",
  "value3": "Turn Number"
}

###
POST http://91.196.248.242:9876/civ6