GET http://blztelbot.herokuapp.com/send-message?chatId=-601860434&msg=111

###
POST http://localhost:9876/civ6

###
POST http://localhost:9876/civ6
Content-Type: application/json

{
  "value1": "Game Name",
  "value2": "civ_player_1",
  "value3": "111",
  "unknown_prop": 123
}

###
POST https://blztelbot.herokuapp.com/civ6

###
POST http://localhost:9876/civ6
Content-Type: application/json

{
  "value1": "Anton_Dima_Artem_artem",
  "value2": "Lazm",
  "value3": "1"
}